name: Jira to Teams Report

on:
  workflow_dispatch:   # manual trigger still available
  schedule:
    - cron: "0 6 * * 1"   # Every Monday at 06:00 UTC

jobs:
  jira-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run Jira to Teams report
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_JQL: ${{ secrets.JIRA_JQL }}
          JIRA_FIELDS: ${{ secrets.JIRA_FIELDS }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TITLE: "Weekly Jira Report"
          TIMEZONE: "UTC"
          # Optional extras:
          # EXPAND: "changelog"
          # RECONCILE_ISSUE_IDS: "10001,10042"
          # JIRA_USE_LEGACY: "true"
          # reliability knobs:
          TEAMS_MESSAGE_MODE: "plain"   # try "plain" first; switch back to "card" if you like
          TEAMS_PROBE: "false"
          TEAMS_CHUNK_LIMIT: "10000"
          # Rank fields (adjust if your Jira uses different IDs)
          # PARENT_RANK_FIELD: "customfield_10015"
          # ISSUE_RANK_FIELD: "customfield_10015"
          # Sort controls
          GROUP_BY_PARENT: "true"
          SORT_CHILDREN_BY_RANK: "true"
          GROUP_STRIP_PARENT_SUMMARY: "true"
          AUTO_DETECT_RANK: "true"   # default, but set explicitly for this test
          # Temporary: print ordering to logs
          DEBUG_ORDER: "true"
        run: python jira_to_teams_report.py
